apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 5 # deemand
  selector: # it helps to adopt pods
    app: myapp
  template: # it helps to create pods
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx
          ports:
             - containerPort: 80
      
          
