# it does support condition
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 3
  selector:
    matchExpressions:
     - key: env 
       operator: In
       values: [dev,test]
  template:
    metadata:
      labels:
       env: test
    spec:
     containers:
      - name: myapp-container
        image: nginx
        ports:
          - containerPort: 80
